### ISSUE TITLE
Better Camelia buttefly File icons for Perl 6 file types

### ISSUE THREAD

**Issue by azawawi** [azawawi/atom-perl6-editor-tools#13]
- Color suggestion: [Bikeshed brown](https://www.google.com/search?q=Bikeshed+brown&ie=utf-8&oe=utf-8).
- Outline instead of detail

Please see https://raw.githubusercontent.com/DanBrooker/file-icons/master/file-icons.png

**Comment by azawawi** [comment]
This is not working on startup because of a [bug](https://github.com/atom/tree-view/issues/732) in atom tree view component.

**Comment by azawawi** [comment]
Fixed in https://github.com/azawawi/atom-perl6-editor-tools/commit/fa0339e332cb951e0c5d559e55d604eda95bb928. Please see https://github.com/atom/tree-view/issues/732#issuecomment-192552853.

**Comment by Alhadis** [comment]
I added Camelia in an [update to the File Icons](https://github.com/DanBrooker/file-icons/releases/tag/v1.7.6) package last week, BTW. =)

You're more than welcome to use the SVG I made for the icon, they can [download it](https://github.com/DanBrooker/file-icons/releases/download/v1.7.6/Icon-SVGs-v1.7.6.zip) from the release page.

**Comment by azawawi** [comment]
Thanks for the update. I will simply add `file-icons` as a dependency and remove local changes.

**Comment by azawawi** [comment]
Done. Sorry for the late reply 👍

**Comment by Alhadis** [comment]
No problem. =) *continues writing hairy Perl 5 one-liners in Makefiles*

**Comment by azawawi** [comment]
:)
