### ISSUE TITLE
Error: spawn perl6 ENOENT

### ISSUE THREAD

**Issue by HotelCalifornia** [azawawi/atom-perl6-editor-tools#26]
Whenever I type code, I get spammed with this error:

```
Error: spawn perl6 ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

Here's a picture:
![Here's a picture](http://puu.sh/oL8Nb/b609b63c3e.png)

Also, when trying to use the POD preview utility, I am told `No Perl 6 editor found. Aborting...`.

**Comment by azawawi** [comment]
Can you please share the code that is causing this?

**Comment by HotelCalifornia** [comment]
This happens with any code, including a simple
    "hello world".say

**Comment by HotelCalifornia** [comment]
I was getting this when I started with a `"hello world".say` (I swear!), but now I'm not...

[here's a gist of the code in the picture](https://gist.github.com/HotelCalifornia/6b3a47b4da97555d9781e8116e3fd909)

**Comment by azawawi** [comment]
Thanks for reporting it and sorry for the late reply. The problem happened to me today. It is related to opening atom from an Ubuntu shortcut and not from a terminal directory (i.e. `$ project-dir> atom .`). I will try to fix it later today.

**Comment by azawawi** [comment]
This seems to have been fixed in linter package. Closing. Please reopen if you find otherwise.

And sorry for the late reply 👍
