### ISSUE TITLE
syntax-check-linter.js problem #2

### ISSUE THREAD

**Issue by J3Rik0** [azawawi/atom-perl6-editor-tools#28]
TypeError: Cannot read property 'endsWith' of undefined
TypeError: Cannot read property 'endsWith' of undefined
    at C:/Users/#####/.atom/packages/atom-perl6-editor-tools/lib/syntax-check-linter.js:38:24
    at process._tickCallback (node.js:392:9)

**Comment by azawawi** [comment]
Fixed. Sorry for being late 👍
