### ISSUE TITLE
Error while compiling - Undeclared routine

### ISSUE THREAD

**Issue by J3Rik0** [azawawi/atom-perl6-editor-tools#29]
And this is all I have in my file

```
#! usr/bin/env perl6
use v6;
say "Hello world" ~ "noire text";
```

`Error: ===SORRY!=== Argument to "say" seems to be malformed at -:3 ------> say Other potential difficulties: Unsupported use of bare "say"; in Perl 6 please use .say if you meant $_, or use an explicit invocant or argument, or use &say to refer to the function as a noun at -:3 ------> say
Error: ===SORRY!===
Argument to "say" seems to be malformed
at -:3
------> say<HERE> 
Other potential difficulties:
    Unsupported use of bare "say"; in Perl 6 please use .say if you meant $_, or use an explicit invocant or argument, or use &say to refer to the function as a noun
    at -:3
    ------> say<HERE>
    at ChildProcess.<anonymous> (C:\Users\#####\.atom\packages\atom-perl6-editor-tools\node_modules\atom-linter\node_modules\sb-exec\lib\index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)`

**Comment by azawawi** [comment]
Sorry for the late response. Fixed with [v0.10.0](https://github.com/azawawi/atom-perl6-editor-tools/releases/tag/v0.10.0). Please reopen if needed.

Your example also needed to be the following:
```Perl6
#! /usr/bin/env perl6
use v6;
say "Hello world" ~ "noire text";
```
