### ISSUE TITLE
Syntax checker doing something weird

### ISSUE THREAD

**Issue by LLFourn** [azawawi/atom-perl6-editor-tools#3]
I just opened one of my existing projects.

![image](https://cloud.githubusercontent.com/assets/3734083/12867842/bfdbee42-cd4c-11e5-97b2-486ce7060065.png)

**Comment by azawawi** [comment]
Try reverting https://github.com/MadcapJake/atom-perl6-editor-tools/commit/f5621fc036b2f528b7fbdd3e40cfac524ec8e440#diff-bea8ace7b9cef06cb1df969f101317bdR22. Could you provide a sample script that causes this behavior?

**Comment by azawawi** [comment]
@LLFourn  Any update on this one?

Seems to me like a filesystem permission issue

**Comment by LLFourn** [comment]
I don't think it's a permissions issue. I don't want it to create "/lib/.precomp". It shouldn't have permission to do that. I tried opening a blank .p6 file and I get:

![image](https://cloud.githubusercontent.com/assets/3734083/12914660/ddd75e0c-cf79-11e5-8d92-e9dd04d3c3e2.png)

So you're right that it's getLibDir that's the problem. I'm not sure how to revert to anything as I installed it via the atom gui (I've never used atom before).

**Comment by azawawi** [comment]
Thanks for the reply. Cool this should be fixed on latest. Let me finish the coffeescript to es6 refactor and then I will publish another release.

**Comment by LLFourn** [comment]
Thanks!

**Comment by azawawi** [comment]
Should be fixed with 0.9.6 via #7. Please update and reopen if needed.

Have a nice day :+1:
