### ISSUE TITLE
Linter includes terminal error codes as text

### ISSUE THREAD

**Issue by con-mo8** [azawawi/atom-perl6-editor-tools#30]
![screen shot 2016-11-18 at 10 26 07 am](https://cloud.githubusercontent.com/assets/15649254/20426965/8312f42a-ad79-11e6-9483-129c0fd64467.png)

Within syntax-check-linter.js where the Rakudo command is defined it would be a lot cleaner if the environment variable RAKUDO_ERROR_COLOR=0 was set. This way the error reporting will look a lot cleaner.

**Comment by con-mo8** [comment]
#28 is related the regex here https://github.com/azawawi/atom-perl6-editor-tools/blob/master/lib/syntax-check-linter.js#L43 is essentially not matching because the manipulation of the error string is not working with the colour codes in there.

**Comment by azawawi** [comment]
Perfect. I will do that now. Better late than never 👍
