### ISSUE TITLE
error when opening a Perl6 file

### ISSUE THREAD

**Issue by cognominal** [azawawi/atom-perl6-editor-tools#32]
Uncaught TypeError: fs.isSymbolicLinkSync is not a function
/home/cog/.atom/packages/atom-perl6-editor-tools/lib/file-icons.js:16

**Comment by azawawi** [comment]
Could you list the Perl 6 example that caused that error?

**Comment by azawawi** [comment]
Fixed in https://github.com/azawawi/atom-perl6-editor-tools/commit/a1f8b5b55b07e9d9bc5dc400db4a88f18c4812f0. Please update.
