### ISSUE TITLE
Timeout and error messages

### ISSUE THREAD

**Issue by holli-holzer** [azawawi/atom-perl6-editor-tools#37]
This is probably not a bug per se, but the behaviour is quite obnoxious.

Compiling code files with lots of custom operators takes a while. When working with such files the linter is timing out and throws an error message. Again, and again and again and... It's really quite annoying.
But the worst part is, if it manages to lint at times and there is an error in the code at that point, it will display this error forever.

Possible solutions: React to a 'do not lint' directive in the code somewhere. Increase the timeout. suppress this error message.

i'd favor the first.
![bildschirmfoto vom 2017-10-28 21-02-46](https://user-images.githubusercontent.com/10507096/32137640-0fda7234-bc24-11e7-9330-f8cf64b936e4.png)

**Comment by azawawi** [comment]
Closing this one since I am going to work more on [`ide-perl6`](https://github.com/azawawi/ide-perl6) and deprecate this plugin. Sorry for the long reply.  :+1:
